name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Get branch
        uses: nelonoel/branch-name@v1.0.1

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Quba ${{ steps.version.outputs.version-without-v }}
          token: ${{ secrets.RELEASE_TOKEN }}
          prerelease: ${{ env.BRANCH_NAME != 'master' }}
